import { describe, expect, it } from "vitest";
import { createEmptyWorkspace } from "@/lib/seed-data";
import { buildEvidencePackMarkdown } from "@/lib/evidence-report";
import type { ContractExperiment, ExperimentVerification } from "@/lib/types";

const SNAPSHOT_HASH = `0x${"a".repeat(64)}`;
const CURRENT_HASH = `0x${"c".repeat(64)}`;
const SNAPSHOT_ADDRESS = `0x${"b".repeat(40)}`;
const CURRENT_ADDRESS = `0x${"d".repeat(40)}`;
const workspace = createEmptyWorkspace();
const verification: ExperimentVerification = {
  snapshot: {
    version: 1,
    transactionHash: SNAPSHOT_HASH,
    contractAddress: SNAPSHOT_ADDRESS,
    manualStatus: "finalized"
  },
  source: "genlayer-rpc",
  rpcUrl: "https://studio.genlayer.com/api",
  rpcProfile: "studionet",
  transactionStatusDialect: "positional",
  receiptCapability: "unsupported",
  contractStateCapability: "unsupported",
  checkedAt: "2026-07-30T00:00:00.000Z",
  transactionFound: true,
  receiptAvailable: false,
  observedStatus: "FINALIZED",
  observedStatusCode: null,
  statusMatchesManual: true,
  observedRecipient: "",
  contractLookup: "not_checked",
  contractStateResult: "",
  result: "verified",
  errorMessage: ""
};
const experiment: ContractExperiment = {
  id: "e",
  contractName: "Scout contract",
  studioFileName: "scout.py",
  deployedContractAddress: CURRENT_ADDRESS,
  transactionHash: CURRENT_HASH,
  status: "accepted",
  experimentNotes: "",
  evidenceUrl: "",
  portalSubmissionNotes: "",
  createdAt: "2026-01-01",
  updatedAt: "2026-01-01",
  verification
};

describe("evidence report", () => {
  it("includes the manual note and selected experiment details", () => {
    const text = buildEvidencePackMarkdown({
      evidencePack: workspace.evidencePack,
      experiment: { ...experiment, verification: undefined }
    });
    expect(text).toContain("> Provenance:");
    expect(text).toContain("Scout contract");
    expect(text).toContain(CURRENT_HASH);
  });

  it("renders immutable snapshot values instead of mutable experiment values", () => {
    const text = buildEvidencePackMarkdown({
      evidencePack: workspace.evidencePack,
      experiment
    });
    const verificationSection = text.slice(text.indexOf("## Verification snapshot"));

    expect(verificationSection).toContain("## Verification snapshot");
    expect(verificationSection).toContain("Snapshot version:** 1");
    expect(verificationSection).toContain(SNAPSHOT_HASH);
    expect(verificationSection).toContain(SNAPSHOT_ADDRESS);
    expect(verificationSection).toContain("Checked manual status:** finalized");
    expect(verificationSection).not.toContain(CURRENT_HASH);
    expect(verificationSection).not.toContain(CURRENT_ADDRESS);
    expect(verificationSection).not.toContain("Recorded status:** accepted");
    expect(verificationSection).toContain("Observed status:** FINALIZED");
    expect(verificationSection).toContain("Recorded status:** finalized");
    expect(verificationSection).toContain("RPC profile:** Studionet");
    expect(verificationSection).toContain("request format:** Positional");
    expect(verificationSection).toContain("Receipt method:** Unsupported by this endpoint");
    expect(verificationSection).toContain("Contract-state method:** Unsupported by this endpoint");
    expect(verificationSection).toContain("Result:** Verified");
    expect(verificationSection).not.toContain("Receipt recipient");
    expect(verificationSection).not.toContain("Receipt routing");
    expect(verificationSection).not.toContain("Contract-state lookup");
    expect(verificationSection).not.toContain("endpoint returned a string");
    expect(verificationSection).toContain(
      "Scope: this check confirms the lifecycle status returned by the selected RPC endpoint for the captured inputs."
    );
    expect(verificationSection).toContain("Generated by GenLayer Scout v0.2.1.");
  });


  it("humanizes not_checked capability values", () => {
    const text = buildEvidencePackMarkdown({
      evidencePack: workspace.evidencePack,
      experiment: {
        ...experiment,
        verification: {
          ...verification,
          receiptCapability: "not_checked",
          contractStateCapability: "not_checked"
        }
      }
    });

    expect(text).toContain("Receipt method:** Not checked");
    expect(text).toContain("Contract-state method:** Not checked");
    expect(text).not.toContain("not_checked");
  });

  it("includes a no-experiment note", () => {
    const text = buildEvidencePackMarkdown({
      evidencePack: workspace.evidencePack
    });
    expect(text).toContain("No experiment selected");
  });
});
