import type { ExperimentStatus, ExperimentVerification } from "@/lib/types";
interface VerifyInput { rpcUrl: string; transactionHash: string; manualStatus: ExperimentStatus; manualContractAddress: string; }
interface RpcReply { result?: unknown; error?: { code?: number; message?: string } }
async function rpc(url: string, method: string, hash: string): Promise<RpcReply> { const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params: [hash] }) }); if (!response.ok) throw new Error(`RPC returned HTTP ${response.status}.`); return response.json() as Promise<RpcReply>; }
function record(value: unknown): Record<string, unknown> | null { return value !== null && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null; }
function findString(value: unknown, keys: string[]) { const item = record(value); if (!item) return ""; for (const key of keys) if (typeof item[key] === "string") return item[key] as string; return ""; }
function statusData(value: unknown) { if (typeof value === "string") return { raw: value, code: null as number | null }; if (typeof value === "number") return { raw: String(value), code: value }; const item = record(value); const nested = item && (record(item.status) ?? record(item.transactionStatus)); const raw = item ? findString(item, ["status", "transactionStatus", "state", "name"]) || findString(nested, ["status", "state", "name"]) : ""; const candidate = item?.statusCode ?? item?.code ?? nested?.code; return { raw, code: typeof candidate === "number" ? candidate : null }; }
function comparableStatus(raw: string): ExperimentStatus | null { const value = raw.trim().toUpperCase(); if (value === "ACCEPTED") return "accepted"; if (value === "FINALIZED") return "finalized"; if (["FAILED", "CANCELED", "CANCELLED"].includes(value)) return "failed"; return null; }
function isNotFound(reply: RpcReply) { const message = reply.error?.message?.toLowerCase() ?? ""; return reply.result === null || reply.error?.code === -32001 || message.includes("not found") || message.includes("unknown transaction"); }
export async function verifyGenLayerTransaction(input: VerifyInput): Promise<ExperimentVerification> {
  const base: ExperimentVerification = { source: "genlayer-rpc", rpcUrl: input.rpcUrl.trim(), checkedAt: new Date().toISOString(), transactionFound: false, receiptAvailable: false, observedStatus: "", observedStatusCode: null, statusMatchesManual: null, observedContractAddress: "", addressMatchesManual: null, result: "manual_only", errorMessage: "" };
  if (!base.rpcUrl || !input.transactionHash.trim()) return { ...base, errorMessage: "An RPC URL and transaction hash are required." };
  try { const statusReply = await rpc(base.rpcUrl, "gen_getTransactionStatus", input.transactionHash.trim()); if (isNotFound(statusReply)) return { ...base, result: "not_found", errorMessage: "The transaction was not found by this RPC endpoint." }; if (statusReply.error) return { ...base, result: "unavailable", errorMessage: `Status lookup failed: ${statusReply.error.message || "RPC error"}.` }; const observed = statusData(statusReply.result); const mapped = comparableStatus(observed.raw); let output: ExperimentVerification = { ...base, transactionFound: true, observedStatus: observed.raw || "Available (status label not returned)", observedStatusCode: observed.code, statusMatchesManual: mapped ? mapped === input.manualStatus : null, result: "verified" };
    try { const receipt = await rpc(base.rpcUrl, "gen_getTransactionReceipt", input.transactionHash.trim()); if (!receipt.error && receipt.result !== null && receipt.result !== undefined) { const address = findString(receipt.result, ["contractAddress", "recipient", "to", "address"]); output = { ...output, receiptAvailable: true, observedContractAddress: address, addressMatchesManual: address && input.manualContractAddress.trim() ? address.toLowerCase() === input.manualContractAddress.trim().toLowerCase() : null }; } } catch { /* Keep valid status evidence. */ }
    if (output.statusMatchesManual === false || output.addressMatchesManual === false) output.result = "mismatch"; return output;
  } catch (error) { return { ...base, result: "unavailable", errorMessage: error instanceof Error ? error.message.slice(0, 240) : "The RPC request could not be completed." }; }
}
