import { describe, expect, it } from "vitest";
import { createEmptyWorkspace } from "@/lib/seed-data";
import { loadWorkspace, parseBackupFile, SCOUT_STORAGE_KEY } from "@/lib/storage";
const experiment = { id: "e1", contractName: "Contract", studioFileName: "contract.py", deployedContractAddress: "0xabc", transactionHash: "0xhash", status: "finalized" as const, experimentNotes: "notes", evidenceUrl: "", portalSubmissionNotes: "", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" };
describe("storage", () => {
  it("parses current backups and experiments without verification", () => { const workspace = { ...createEmptyWorkspace(), experiments: [experiment] }; expect(parseBackupFile(JSON.stringify({ app: "GenLayer Scout", workspace })).workspace?.experiments[0]).toMatchObject(experiment); });
  it("rejects malformed JSON and invalid schemas", () => { expect(parseBackupFile("{").workspace).toBeNull(); expect(parseBackupFile(JSON.stringify({ schemaVersion: 99 })).workspace).toBeNull(); });
  it("accepts valid verification and drops invalid verification", () => { const verification = { source: "genlayer-rpc" as const, rpcUrl: "https://rpc", checkedAt: "2026-01-01", transactionFound: true, receiptAvailable: false, observedStatus: "FINALIZED", observedStatusCode: null, statusMatchesManual: true, observedContractAddress: "", addressMatchesManual: null, result: "verified" as const, errorMessage: "" }; const valid = parseBackupFile(JSON.stringify({ ...createEmptyWorkspace(), experiments: [{ ...experiment, verification }] })).workspace!; expect(valid.experiments[0].verification).toEqual(verification); const invalid = parseBackupFile(JSON.stringify({ ...createEmptyWorkspace(), experiments: [{ ...experiment, verification: { nope: true } }] })).workspace!; expect(invalid.experiments[0].verification).toBeUndefined(); });
  it("migrates legacy data, drops demos, and preserves fields", () => { const values = new Map<string,string>(); values.set("genlayer-scout-v0.1", JSON.stringify({ runs: [{ id: "run-demo-1", status: "finalized" }, { id: "legacy", contractName: "Kept", fileName: "kept.py", deployedAddress: "0x1", transactionHash: "0x2", status: "accepted", notes: "preserved", evidenceUrl: "url", createdAt: "2025-01-01" }] })); const storage = { getItem: (k:string) => values.get(k) ?? null, setItem: (k:string,v:string) => values.set(k,v), removeItem: (k:string) => values.delete(k), clear: () => values.clear(), key: () => null, length: values.size } as Storage; const result = loadWorkspace(storage); expect(result.workspace.experiments).toHaveLength(1); expect(result.workspace.experiments[0]).toMatchObject({ id: "legacy", contractName: "Kept", studioFileName: "kept.py", experimentNotes: "preserved" }); expect(storage.getItem(SCOUT_STORAGE_KEY)).toBeNull(); });
});
